#!/usr/bin/env bash

synclient TapButton1=1 TapButton2=3 TapButton3=2 HorizEdgeScroll=1

xhost +local:root

if [ -x /usr/bin/dbus-launch -a -z "${DBUS_SESSION_BUS_ADDRESS}" ]; then
	eval `dbus-launch --sh-syntax --exit-with-session`
	export DBUS_SESSION_BUS_ADDRESS
	export DBUS_SESSION_BUS_PID
fi

# launch tint2
if [ -f ~/.config/tint2/tint2rc ]; then
	tint2 &
else
	tint2 -c /usr/etc/xdg/tint2/tint2rc &
fi

# Pulse first
if which pulseaudio >/dev/null 2>&1; then
	pulseaudio --exit-idle-time=-1 --log-target=syslog &
else
	# launch volumeicon if found
	if which volumeicon >/dev/null 2>&1; then
		volumeicon &
	fi
fi

# Screen setup
# Explaination:
# * I use an ultra-wide display as my main monitor connected through usb-C (xrand detect is as DP).
# * The conditional detects the ultra-wide so mark it as primary and sets a wallpaper according to its resolution
# * If no display is attached then it sets a "single" lower resolution background
displays=$(xrandr | grep " connected" | wc -l)
if [ "${displays}" = "2" ]; then
	eDP=$(xrandr | awk '/^eDP.* connected/ {print $1}')
	dev=$(xrandr | awk '/^DP.* connected/ {print $1}')
	xrandr -d $DISPLAY --output ${dev} --left-of ${eDP} --auto
	xrandr --output ${dev} --primary
	hsetroot -fill ~/.local/wallpapers/aurora.png &
else
	hsetroot -center ~/.local/wallpapers/default &
fi

# launch conky (if you want conky, just uncomment this)
if which conky >/dev/null 2>&1; then
	conky &
fi


